const lesson_site =
  [ { lesson_id: 3, site_id: 2, date: '2019-01-03T08:00:00.000Z' },
    { lesson_id: 4, site_id: 2, date: '2019-01-04T08:00:00.000Z' },
    { lesson_id: 5, site_id: 3, date: '2019-01-05T08:00:00.000Z' },
    { lesson_id: 6, site_id: 3, date: '2019-01-06T08:00:00.000Z' },
    { lesson_id: 7, site_id: 3, date: '2019-01-07T08:00:00.000Z' }
]
const lessons =  [ { id: 1,
                        title: 'Variables',
                        summary: 'Introduction to variables ',
                        link: 'http://tinyurl.com/variables' },
                      { id: 2,
                        title: 'Loops',
                        summary: 'For loops and while loops',
                        link: 'http://tinyurl.com/loops' },
                      { id: 3,
                        title: 'Lists:1',
                        summary: 'First lesson on lists',
                        link: 'http://tinyurl.com/lists1' },
                      { id: 4,
                        title: 'Introduction to HTML',
                        summary: 'Create personal websites',
                        link: 'http://tinyurl.com/html_sites' },
                      { id: 5,
                        title: 'CSS',
                        summary: 'Add color changes and more to personal websites',
                        link: 'http://tinyurl.com/css_color' },
                      { id: 6,
                        title: 'Control Statements',
                        summary: 'Learn If and If Else Statements',
                        link: 'http://tinyurl.com/if_else' },
                      { id: 7,
                        title: 'Functions',
                        summary: 'Learn to create your own functions',
                        link: 'http://tinyurl.com/functions' } ];
const sitelessons = [ { title: 'Introduction to HTML',
                           summary: 'Create personal websites',
                           link: 'http://tinyurl.com/html_sites',
                           date: '2019-01-05T08:00:00.000Z' },
                         { title: 'CSS',
                           summary: 'Add color changes and more to personal websites',
                           link: 'http://tinyurl.com/css_color',
                           date: '2019-01-06T08:00:00.000Z' } ];
const newLesson = {"title":"Algorithms","summary":"Face Off Activity","link":"http://tinyurl.com/algorithms"};
const newLessons = [ { id: 1,
                                           title: 'Variables',
                                           summary: 'Introduction to variables ',
                                           link: 'http://tinyurl.com/variables' },
                                         { id: 2,
                                           title: 'Loops',
                                           summary: 'For loops and while loops',
                                           link: 'http://tinyurl.com/loops' },
                                         { id: 3,
                                           title: 'Lists:1',
                                           summary: 'First lesson on lists',
                                           link: 'http://tinyurl.com/lists1' },
                                         { id: 4,
                                           title: 'Introduction to HTML',
                                           summary: 'Create personal websites',
                                           link: 'http://tinyurl.com/html_sites' },
                                         { id: 5,
                                           title: 'CSS',
                                           summary: 'Add color changes and more to personal websites',
                                           link: 'http://tinyurl.com/css_color' },
                                         { id: 6,
                                           title: 'Control Statements',
                                           summary: 'Learn If and If Else Statements',
                                           link: 'http://tinyurl.com/if_else' },
                                         { id: 7,
                                           title: 'Functions',
                                           summary: 'Learn to create your own functions',
                                           link: 'http://tinyurl.com/functions' },
                                            { id: 8,
                                              title: 'Algorithms',
                                              summary: 'Face Off Activity',
                                              link: 'http://tinyurl.com/algorithms' }];
const newret = {"title":"Algorithms"};
const newSiteLesson = {"lesson_id" : 7, "site_id" : 1, "date":"2019-01-07T08:00:00.000Z" };
const newSLessons = [ { id: 1,
                           lesson_id: 4,
                           site_id: 1,
                           date: '2019-01-06T08:00:00.000Z' },
                         { id: 2,
                           lesson_id: 5,
                           site_id: 1,
                           date: '2019-01-05T08:00:00.000Z' },
                         { id: 3,
                           lesson_id: 4,
                           site_id: 2,
                           date: '2019-01-05T08:00:00.000Z' },
                         { id: 4,
                           lesson_id: 5,
                           site_id: 2,
                           date: '2019-01-06T08:00:00.000Z' },
                         { id: 5,
                           lesson_id: 4,
                           site_id: 3,
                           date: '2019-01-05T08:00:00.000Z' },
                         { id: 6,
                           lesson_id: 5,
                           site_id: 3,
                           date: '2019-01-06T08:00:00.000Z' },
                         { id: 7,
                           lesson_id: 1,
                           site_id: 4,
                           date: '2019-01-05T08:00:00.000Z' },
                         { id: 8,
                           lesson_id: 2,
                           site_id: 4,
                           date: '2019-01-06T08:00:00.000Z' },
                         { id: 9,
                           lesson_id: 3,
                           site_id: 4,
                           date: '2019-01-05T08:00:00.000Z' },
                         { id: 10,
                           lesson_id: 6,
                           site_id: 4,
                           date: '2019-01-06T08:00:00.000Z' },
                         { id: 11,
                           lesson_id: 7,
                           site_id: 4,
                           date: '2019-01-05T08:00:00.000Z' },
                         { id: 12,
                           lesson_id: 1,
                           site_id: 5,
                           date: '2019-01-05T08:00:00.000Z' },
                         { id: 13,
                           lesson_id: 2,
                           site_id: 5,
                           date: '2019-01-06T08:00:00.000Z' },
                         { id: 14,
                           lesson_id: 3,
                           site_id: 5,
                           date: '2019-01-05T08:00:00.000Z' },
                         { id: 15,
                           lesson_id: 6,
                           site_id: 5,
                           date: '2019-01-06T08:00:00.000Z' },
                         { id: 16,
                           lesson_id: 7,
                           site_id: 5,
                           date: '2019-01-05T08:00:00.000Z' },
                         { id: 17,
                           lesson_id: 7,
                           site_id: 2,
                           date: '2019-01-07T08:00:00.000Z' } ];
const rosterMentor = [{"name":"user1","email":"user1@email.com","picture":null,"grade":13,"bio":null,"notes":"Fall 2019, Montera"}];
const rosterStudent = [ { name: 'user2',
                             email: 'user2@email.com',
                             picture: null,
                             grade: 12,
                             bio: null,
                             notes: 'Fall 2019, Fremont High' } ];
const profile1 = [{"email": "user1@email.com", "picture": null, "grade": 13, "name": "user1", "bio": null, "notes": "Fall 2019, Montera"}];
const updatedNotes = {"notes": "Spring 2020, Montera", "id": 1, "grade": 13, "bio": "this is a new bio"};
const updatedProfile = [{"email": "user1@email.com", "picture": null, "grade": 13, "name": "user1", "bio": "this is a new bio", "notes": "Spring 2020, Montera"}];
const all_sites = [ { schoolName: 'DCA' },
                       { schoolName: 'Montera' },
                       { schoolName: 'Willard' },
                       { schoolName: 'Fremont High' },
                       { schoolName: 'Rudsdale' },
                       { schoolName: 'Roosevelt' },
                       { schoolName: 'Lighthouse Charter' },
                       { schoolName: 'College Track' },
                       { schoolName: 'Squash Drive' },
                       { schoolName: 'Oakland Tech' } ];

module.exports = {
  lessons,
  sitelessons,
  newLesson,
  newret,
  newLessons,
  newSiteLesson,
  newSLessons,
  rosterMentor,
  rosterStudent,
  profile1,
  updatedNotes,
  updatedProfile,
  lesson_site,
  all_sites
};
