module.exports = [
  {
    email: 'user1@email.com',
    name: 'user1',
    notes: 'Fall 2019, Montera',
    role: 'mentor',
  },
  {
    email: 'user2@email.com',
    name: 'user2',
    notes: 'Fall 2019, Fremont High',
    role: 'student',
  },
  {
    email: 'user3@email.com',
    name: 'user3',
    notes: 'Fall 2019, Oakland Tech',
    role: 'student',
  },
  {
    email: 'user4@email.com',
    name: 'user4',
    notes: 'Fall 2019, Squash Drive',
    role: 'mentor',
  },
  {
    email: 'user5@email.com',
    name: 'user5',
    notes: 'Fall 2019, Willard',
    role: 'student',
  },
  {
    email: 'user6@email.com',
    name: 'user6',
    notes: 'Fall 2019, Montera',
    role: 'mentor',
  },
  {
    email: 'user7@email.com',
    name: 'user7',
    notes: 'Fall 2019, Montera',
    role: 'mentor',
  },
  {
    email: 'user8@email.com',
    name: 'user8',
    notes: 'Fall 2019, Montera',
    role: 'mentor',
  },
  {
    email: 'user9@email.com',
    name: 'user9',
    notes: 'Fall 2019, Montera',
    role: 'mentor',
  },
  {
    email: 'user10@email.com',
    name: 'user10',
    notes: 'Fall 2019, Montera',
    role: 'student',
  },
  {
    email: 'user11@email.com',
    name: 'user11',
    notes: 'Fall 2019, Montera',
    role: 'student',
  },
  {
    email: 'user12@email.com',
    name: 'user12',
    notes: 'Fall 2019, Montera',
    role: 'student',
  },
  {
    email: 'user13@email.com',
    name: 'user13',
    notes: 'Fall 2019, Montera',
    role: 'student',
  },
  {
    email: 'user14@email.com',
    name: 'user14',
    notes: 'Fall 2019, Montera',
    role: 'student',
  },
  {
    email: 'user15@email.com',
    name: 'user15',
    notes: 'Fall 2019, Montera',
    role: 'student',
  },
  {
    email: 'user16@email.com',
    name: 'user16',
    notes: 'Fall 2019, Montera',
    role: 'student',
  },
  {
    email: 'user17@email.com',
    name: 'user17',
    notes: 'Fall 2019, Montera',
    role: 'student',
  },
  {
    email: 'user18@email.com',
    name: 'user18',
    notes: 'Fall 2019, Montera',
    role: 'student',
  },
  {
    email: 'user19@email.com',
    name: 'user19',
    notes: 'Fall 2019, Montera',
    role: 'student',
  },
  {
    email: 'user20@email.com',
    name: 'user20',
    notes: 'Fall 2019, Montera',
    role: 'student',
  },
];
